apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-calculo-risco
  labels:
    app: ml-calculo-risco
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-calculo-risco
  template:
    metadata:
      labels:
        app: ml-calculo-risco
    spec:
      containers:
        - name: ml-calculo-risco
          image: docker.io/aggosistemas/ml-calculo-risco:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
